version: '3'
services:
# MongoDB: https://hub.docker.com/_/mongo/
  mongo:
    container_name: graylog_mongodb
    image: mongo:5.0.13    
    volumes:
      - /Users/dayane/Documents/Dev/Treinamentos/Graylog/graylog/data/mongo_data:/data/db
    networks:
      - graylog

# Elasticsearch: https://www.elastic.co/guide/en/elasticsearch/reference/7.10/docker.html
  elasticsearch:
    container_name: graylog_elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.10.2
    environment:
        - http.host=0.0.0.0
        - transport.host=localhost
        - network.host=0.0.0.0
        - "ES_JAVA_OPTS=-Dlog4j2.formatMsgNoLookups=true -Xms512m -Xmx512m"
    volumes:
      - /Users/dayane/Documents/Dev/Treinamentos/Graylog/graylog/data/es_data:/usr/share/elasticsearch/data
    ulimits:
      memlock:
        soft: -1
        hard: -1
    deploy:
      resources:
        limits:
          memory: 1g
    networks:
        - graylog

# Graylog: https://hub.docker.com/r/graylog/graylog/
  graylog:
    container_name: graylog
    image: graylog/graylog:5.1
    environment:
    # CHANGE ME (must be at least 16 characters)!
      - GRAYLOG_PASSWORD_SECRET=somepasswordpepper
    # Password: admin
      - GRAYLOG_ROOT_PASSWORD_SHA2=8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918
      - GRAYLOG_HTTP_EXTERNAL_URI=http://127.0.0.1:9000/
      - GRAYLOG_WEB_ENDPOINT_URI=http://127.0.0.1:9000/api
    # Outras configurações
      - GRAYLOG_TIMEZONE=America/Sao_Paulo      
    volumes:
      # CASO SEJA A PRIMEIRA VEZ DO CONTAINER E NÃO TIVER OS ARQUIVOS É NECESSÁRIO CRIAR, PODENDO OBTÊ-lOS COM OS COMANDOS ABAIXO:
      # wget https://raw.githubusercontent.com/Graylog2/graylog-docker/5.0/config/graylog.conf
      # wget https://raw.githubusercontent.com/Graylog2/graylog-docker/5.0/config/log4j2.xml
    # VOLUMES DAS CONFIGURAÇÔES PADRÃO
      - /Users/dayane/Documents/Dev/Treinamentos/Graylog/graylog/data/graylog_config:/usr/share/graylog/data/config
      - /Users/dayane/Documents/Dev/Treinamentos/Graylog/graylog/data/graylog_journal:/usr/share/graylog/data/journal
    entrypoint: /usr/bin/tini -- wait-for-it elasticsearch:9200 -- /docker-entrypoint.sh
    networks:
        - graylog
    links:
      - mongo
      - elasticsearch
    restart: always
    depends_on:
        - mongo
        - elasticsearch
    ports:
# Graylog web interface and REST API
      - 9000:9000
# Syslog TCP
      - 1514:1514
# Syslog UDP
      - 1514:1514/udp
# GELF TCP
      - 12201:12201
      - 5555:5555
      - 5044:5044
# GELF UDP
      - 12201:12201/udp

networks:
  graylog:
    driver: bridge
